version: '3.8'

networks:
  kafka-net:
    external: true

services:
  jobmanager:
    image: flink:1.14.3-scala_2.11-java11
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: "standalone-job --env cluster"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      FLINK_ENV: cluster
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../app/conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints-directory
      - ../data/flink/savepoints:/tmp/flink-savepoints-directory
    networks:
      - kafka-net

  taskmanager:
    image: flink:1.14.3-scala_2.11-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      FLINK_ENV: cluster
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../app/conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints-directory
      - ../data/flink/savepoints:/tmp/flink-savepoints-directory
    networks:
      - kafka-net

