version: '3.8'

networks:
  kafka-net:
    external: true

services:
  jobmanager:
    image: flink:1.14.3-scala_2.11-java11
    hostname: jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
      - "9249:9249"   # Prometheus Exporter
      - "9999:9999"   # JMX Remote Port
    command: "standalone-job --env cluster"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    networks:
      - kafka-net

  taskmanager:
    image: flink:1.14.3-scala_2.11-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground --env cluster"
    ports:
      - "9250-9255:9249"    # Prometheus Exporter
      - "10000-10005:9999"  # JMX Remote Port
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - |
        FLINK_PROPERTIES=
          taskmanager.numberOfTaskSlots: ${NUM_TASK_SLOTS:?err}
          parallelism.default: ${DEFAULT_PARALLELISM:?err}
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    networks:
      - kafka-net

