version: '3.8'

networks:
  kafka-net:
    external: true

services:
  jobmanager:
    image: flink:1.14.3-scala_2.11-java11
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"
    command: "standalone-job --env cluster"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    networks:
      - kafka-net

  taskmanager:
    image: flink:1.14.3-scala_2.11-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground -Dtaskmanager.numberOfTaskSlots=${NUM_TASK_SLOTS:?err}"
    ports:
      - "9250-9255:9249"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      FLINK_ENV_JAVA_OPTS_TM: "-Dparallelism.default=${DEFAULT_PARALLELISM:?err}"
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    networks:
      - kafka-net

