version: '3.8'

networks:
  kafka-net:
    external: true

services:
  jobmanager:
    image: flink:1.17.1-java11
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249" # Prometheus Exporter
    command: "standalone-job -Dparallelism.default=${DEFAULT_PARALLELISM:?err} --env cluster"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    networks:
      - kafka-net

  taskmanager:
    image: flink:1.17.1-java11
    command: "taskmanager.sh start-foreground -Dtaskmanager.numberOfTaskSlots=${NUM_TASK_SLOTS:?err}"
    ports:
      - "9249" # Prometheus Exporter
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
    volumes:
      - ../app/build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints
      - ../data/flink/savepoints:/tmp/flink-savepoints
    depends_on:
      - jobmanager
    networks:
      - kafka-net

