version: '3.8'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  zk1:
    image: zookeeper
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zk1:2888:3888
    volumes:
      - ../data/zookeeper/zk1/data:/data
      - ../data/zookeeper/zk1/datalog:/datalog
    networks:
      - kafka-net
    restart: unless-stopped

  broker-1:
    image: wurstmeister/kafka:latest
    hostname: "broker-1"
    ports:
      - "9092:9092"
      - "9010:9010"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9010"
      JMX_PORT: 9010
    volumes:
      - ../data/kafka/broker-1/data:/var/lib/kafka/data
    depends_on:
      - zk1
    networks:
      - kafka-net
    restart: unless-stopped

  kafka-tools:
    image: confluentinc/cp-kafka:latest
    hostname: "kafka-tools"
    container_name: "kafka-tools"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - broker-1
    networks:
      - kafka-net
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "8001:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker-1:19092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      CMD_ARGS: "--schemaregistry.connect=http://schema-registry:8085 --message.format=AVRO"
    depends_on:
      - "broker-1"
    networks:
      - kafka-net
    restart: unless-stopped
