version: '3.8'

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  zk1:
    image: zookeeper
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zk1:2888:3888
    volumes:
      - ../data/zookeeper/zk1/data:/data
      - ../data/zookeeper/zk1/datalog:/datalog
    networks:
      - kafka-net
    restart: unless-stopped

  broker-1:
    image: wurstmeister/kafka:latest
    hostname: "broker-1"
    container_name: "broker-1"
    ports:
      - "9092:9092"
      - "9900:9900"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: >
        kafka.controller=INFO,
        kafka.producer.async.DefaultEventHandler=INFO,
        state.change.logger=INFO
      KAFKA_JMX_OPTS: > 
        -Dcom.sun.management.jmxremote=true
        -Djava.rmi.server.hostname=broker-1
        -Dcom.sun.management.jmxremote.port=9900
        -Dcom.sun.management.jmxremote.rmi.port=9900
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
    volumes:
      - ../data/kafka/broker-1/data:/var/lib/kafka/data
    depends_on:
      - zk1
    networks:
      - kafka-net
    restart: unless-stopped

  kafka-tools:
    image: confluentinc/cp-kafka:latest
    hostname: "kafka-tools"
    container_name: "kafka-tools"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - broker-1
    networks:
      - kafka-net
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8001:8080
    depends_on:
      - zk1
      - broker-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk1:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8085
      KAFKA_CLUSTERS_0_METRICS_PORT: 9900
    networks:
      - kafka-net
    restart: unless-stopped

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - zk1
      - broker-1
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://broker-1:19092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
    ports:
      - 8085:8085
    networks:
      - kafka-net
    restart: unless-stopped