/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package apache.flink.kotlin.starter

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull("hello world", "app should have a greeting")
    }
}
