/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package apache.flink.kotlin.starter

import org.assertj.core.api.Assertions.*
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun TheAnswerToLife() {
        assertThat(42).isEqualTo(Integer.sum(19, 23))
    }

    @Test
    fun AlwaysRight() {
        assertThat(true).isEqualTo(true)
    }
}
