/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package apache.flink.kotlin.starter

import org.assertj.core.api.Assertions.*
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

@DisplayName("Example Tests")
class ExampleTest {
    @Test
    @DisplayName("the answer to all of life")
    fun TheAnswerToLife() {
        assertThat(42).isEqualTo(Integer.sum(19, 23))
    }

    @Test
    @DisplayName("always right")
    fun AlwaysRight() {
        assertThat(true).isEqualTo(true)
    }
}
