---
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'flink'
    dns_sd_configs:
      - names:
          - jobmanager
          - taskmanager
        type: A
        port: 9249
